[package]
name = "ndarray_example"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15.6"
ndarray-rand = "0.14.0"

[dev-dependencies]
criterion = "0.3"

[[bench]]
name = "my_benchmark"
path = "tests/benchmarks.rs"
harness = false